# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: S:/post/blinkAXI/src/constraints.xdc

# Block Designs: S:/post/blinkAXI/src/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: s:/post/blinkAXI/src/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: s:/post/blinkAXI/src/ip/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_0 || ORIG_REF_NAME==design_1_util_vector_logic_0_0} -quiet] -quiet

# IP: s:/post/blinkAXI/src/ip/design_1_blink_AXI_0_0/design_1_blink_AXI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blink_AXI_0_0 || ORIG_REF_NAME==design_1_blink_AXI_0_0} -quiet] -quiet

# IP: s:/post/blinkAXI/src/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: s:/post/blinkAXI/src/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_50M_0} -quiet] -quiet

# IP: s:/post/blinkAXI/src/ip/design_1_blink_tunable_0_0/design_1_blink_tunable_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blink_tunable_0_0 || ORIG_REF_NAME==design_1_blink_tunable_0_0} -quiet] -quiet

# IP: s:/post/blinkAXI/src/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: S:/post/blinkAXI/src/design_1_ooc.xdc
